name: Lint Code
#adding
on:
  pull_request:
    branches:
      - main  # Specify the branches you want to trigger the workflow on

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '20'

    - run: npm install

    - run: npx eslint .
